const DATABASE_NAME = 'groceriesDB';
const UPDATE_STORE_GROCERY_CATEGORY_API_METHOD = 'UPDATE_STORE_GROCERY_CATEGORY';
const UPDATE_STORE_GROCERY_API_METHOD = 'UPDATE_STORE_GROCERY';
const SUBSCRIBE_TO_STORE_API_METHOD = 'SUBSCRIBE_TO_STORE';
const UNSUBSCRIBE_FROM_STORE_API_METHOD = 'UNSUBSCRIBE_FROM_STORE';
const REORGANIZE_STORE_GROCERIES_API_METHOD = 'REORGANIZE_STORE_GROCERIES';
const DELETE_STORE_CATEGORY_API_METHOD = 'DELETE_STORE_CATEGORY';
const UPDATE_STORE_CATEGORY_API_METHOD = 'UPDATE_STORE_CATEGORY';
const ADD_STORE_GROCERY_API_METHOD = 'ADD_STORE_GROCERY';
const DELETE_STORE_GROCERY_API_METHOD = 'DELETE_STORE_GROCERY';
const UNCATEGORIZED = '__ Uncategorized __';

export { 
    DATABASE_NAME,
    UPDATE_STORE_GROCERY_CATEGORY_API_METHOD,
    UPDATE_STORE_GROCERY_API_METHOD,
    SUBSCRIBE_TO_STORE_API_METHOD,
    UNSUBSCRIBE_FROM_STORE_API_METHOD,
    REORGANIZE_STORE_GROCERIES_API_METHOD,
    UPDATE_STORE_CATEGORY_API_METHOD,
    DELETE_STORE_CATEGORY_API_METHOD,
    ADD_STORE_GROCERY_API_METHOD,
    DELETE_STORE_GROCERY_API_METHOD,
    UNCATEGORIZED
};