const DATABASE_NAME = 'groceriesDB';
const UPDATE_STORE_GROCERY_CATEGORY_API_METHOD = 'UPDATE_STORE_GROCERY_CATEGORY';
const UPDATE_STORE_GROCERY_API_METHOD = 'UPDATE_STORE_GROCERY';
const ADD_STORE_CATEGORY_API_METHOD = 'ADD_STORE_CATEGORY';
const SUBSCRIBE_TO_STORE_API_METHOD = 'SUBSCRIBE_TO_STORE';
const MOVE_STORE_CATEGORY_API_METHOD = 'MOVE_STORE_CATEGORY';
const UNSUBSCRIBE_FROM_STORE_API_METHOD = 'UNSUBSCRIBE_FROM_STORE';
const REORGANIZE_STORE_GROCERIES_API_METHOD = 'REORGANIZE_STORE_GROCERIES';
const DELETE_STORE_CATEGORY_API_METHOD = 'DELETE_STORE_CATEGORY';
const UPDATE_STORE_CATEGORY_API_METHOD = 'UPDATE_STORE_CATEGORY';
const ADD_STORE_GROCERY_API_METHOD = 'ADD_STORE_GROCERY';
const DELETE_STORE_GROCERY_API_METHOD = 'DELETE_STORE_GROCERY';
const CHECK_ACTIVATION_CODE_API_METHOD = 'CHECK_ACTIVATION_CODE';
const UNCATEGORIZED = '__ Uncategorized __';
const NOT_AVAILABLE_AT_STORE = 'Not Available At Store';

const LOCAL_STORAGE_USER = 'GROCERY_USER';

export { 
    DATABASE_NAME,
    
    UPDATE_STORE_GROCERY_CATEGORY_API_METHOD,
    UPDATE_STORE_GROCERY_API_METHOD,
    ADD_STORE_CATEGORY_API_METHOD,
    SUBSCRIBE_TO_STORE_API_METHOD,
    UNSUBSCRIBE_FROM_STORE_API_METHOD,
    REORGANIZE_STORE_GROCERIES_API_METHOD,
    UPDATE_STORE_CATEGORY_API_METHOD,
    DELETE_STORE_CATEGORY_API_METHOD,
    ADD_STORE_GROCERY_API_METHOD,
    DELETE_STORE_GROCERY_API_METHOD,
    MOVE_STORE_CATEGORY_API_METHOD,
    CHECK_ACTIVATION_CODE_API_METHOD,

    UNCATEGORIZED,
    NOT_AVAILABLE_AT_STORE,

    LOCAL_STORAGE_USER
};